package kalex.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kalex.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.04.14 20:08:37 // Generated by ComTest
 *
 */
public class KayttajatTest {



  // Generated by ComTest BEGIN
  /** testLisaa34 */
  @Test
  public void testLisaa34() {    // Kayttajat: 34
    Kayttajat kayttajat = new Kayttajat(); 
    Kayttaja kimi1 = new Kayttaja(), kimi2 = new Kayttaja(); 
    assertEquals("From: Kayttajat line: 37", 0, kayttajat.getLkm()); 
    kayttajat.lisaa(kimi1); assertEquals("From: Kayttajat line: 38", 1, kayttajat.getLkm()); 
    kayttajat.lisaa(kimi2); assertEquals("From: Kayttajat line: 39", 2, kayttajat.getLkm()); 
    assertEquals("From: Kayttajat line: 40", 2, kayttajat.getAlkiot()); 
    kayttajat.lisaa(kimi1); assertEquals("From: Kayttajat line: 41", 3, kayttajat.getLkm()); 
    assertEquals("From: Kayttajat line: 42", 4, kayttajat.getAlkiot()); 
    assertEquals("From: Kayttajat line: 43", kimi1, kayttajat.tuoKayttaja(0)); 
    assertEquals("From: Kayttajat line: 44", kimi2, kayttajat.tuoKayttaja(1)); 
    assertEquals("From: Kayttajat line: 45", kimi1, kayttajat.tuoKayttaja(2)); 
    assertEquals("From: Kayttajat line: 46", false, kayttajat.tuoKayttaja(1) == kimi1); 
    assertEquals("From: Kayttajat line: 47", true, kayttajat.tuoKayttaja(1) == kimi2); 
    kayttajat.lisaa(kimi1); assertEquals("From: Kayttajat line: 48", 4, kayttajat.getLkm()); 
    kayttajat.lisaa(kimi1); assertEquals("From: Kayttajat line: 49", 5, kayttajat.getLkm()); 
    kayttajat.lisaa(kimi1); assertEquals("From: Kayttajat line: 50", 6, kayttajat.getLkm()); 
    kayttajat.lisaa(kimi1); assertEquals("From: Kayttajat line: 51", 7, kayttajat.getLkm()); 
  } // Generated by ComTest END
}