package kalex.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kalex.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.05.19 13:44:08 // Generated by ComTest
 *
 */
public class KayttajanOluetTest {



  // Generated by ComTest BEGIN
  /** testLisaa36 */
  @Test
  public void testLisaa36() {    // KayttajanOluet: 36
    KayttajanOluet kayttajanOluet = new KayttajanOluet(); 
    KayttajanOlut kayttajanOlut = new KayttajanOlut(), kayttajanOlut2 = new KayttajanOlut(); 
    assertEquals("From: KayttajanOluet line: 39", 0, kayttajanOluet.getLkm()); 
    kayttajanOluet.lisaa(kayttajanOlut); assertEquals("From: KayttajanOluet line: 40", 1, kayttajanOluet.getLkm()); 
    kayttajanOluet.lisaa(kayttajanOlut2); assertEquals("From: KayttajanOluet line: 41", 2, kayttajanOluet.getLkm()); 
    assertEquals("From: KayttajanOluet line: 42", 2, kayttajanOluet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoistaOlut207 
   * @throws SailoException when error
   */
  @Test
  public void testPoistaOlut207() throws SailoException {    // KayttajanOluet: 207
    Kayttaja kayttaja = new Kayttaja(); 
    kayttaja.rekisteroi(); kayttaja.kimilleKalexia(); 
    Olut olut = new Olut(); 
    olut.rekisteroi(); olut.karjalatKitusiin(); 
    KayttajanOluet kayttajanOluet = new KayttajanOluet(); 
    KayttajanOlut kayttajanOlut = new KayttajanOlut(); 
    kayttajanOlut.setTestIds(kayttaja.getID(), olut.getId()); kayttajanOlut.kiminKarjala(); 
    kayttajanOluet.lisaa(kayttajanOlut); 
    assertEquals("From: KayttajanOluet line: 217", 1, kayttajanOluet.getLkm()); 
    kayttajanOluet.poistaOlut(kayttajanOlut.getOlutId(), kayttajanOlut.getKayttajaId()); 
    assertEquals("From: KayttajanOluet line: 219", 0, kayttajanOluet.getLkm()); 
  } // Generated by ComTest END
}