package kalex.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kalex.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.03.20 13:32:15 // Generated by ComTest
 *
 */
public class KayttajaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi31 */
  @Test
  public void testRekisteroi31() {    // Kayttaja: 31
    Kayttaja kimi1 = new Kayttaja(); 
    assertEquals("From: Kayttaja line: 33", 0, kimi1.getID()); 
    kimi1.rekisteroi(); 
    Kayttaja kimi2 = new Kayttaja(); 
    kimi2.rekisteroi(); 
    int n1 = kimi1.getID(); 
    int n2 = kimi2.getID(); 
    assertEquals("From: Kayttaja line: 39", n2-1, n1); 
  } // Generated by ComTest END
}