package kalex.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kalex.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.04.14 20:17:19 // Generated by ComTest
 *
 */
public class OluetTest {



  // Generated by ComTest BEGIN
  /** testLisaa33 */
  @Test
  public void testLisaa33() {    // Oluet: 33
    Oluet oluet = new Oluet(); 
    Olut karjala1 = new Olut(), karjala2 = new Olut(); 
    assertEquals("From: Oluet line: 36", 0, oluet.getLkm()); 
    oluet.lisaa(karjala1); assertEquals("From: Oluet line: 37", 1, oluet.getLkm()); 
    oluet.lisaa(karjala2); assertEquals("From: Oluet line: 38", 2, oluet.getLkm()); 
    assertEquals("From: Oluet line: 39", 2, oluet.getAlkiot()); 
    oluet.lisaa(karjala1); assertEquals("From: Oluet line: 40", 3, oluet.getLkm()); 
    assertEquals("From: Oluet line: 41", 4, oluet.getAlkiot()); 
    assertEquals("From: Oluet line: 42", karjala1, oluet.tuoOlut(0)); 
    assertEquals("From: Oluet line: 43", karjala2, oluet.tuoOlut(1)); 
    assertEquals("From: Oluet line: 44", karjala1, oluet.tuoOlut(2)); 
    assertEquals("From: Oluet line: 45", false, oluet.tuoOlut(1) == karjala1); 
    assertEquals("From: Oluet line: 46", true, oluet.tuoOlut(1) == karjala2); 
    oluet.lisaa(karjala1); assertEquals("From: Oluet line: 47", 4, oluet.getLkm()); 
    oluet.lisaa(karjala1); assertEquals("From: Oluet line: 48", 5, oluet.getLkm()); 
    oluet.lisaa(karjala1); assertEquals("From: Oluet line: 49", 6, oluet.getLkm()); 
    oluet.lisaa(karjala1); assertEquals("From: Oluet line: 50", 7, oluet.getLkm()); 
  } // Generated by ComTest END
}