package kalex.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kalex.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.03.31 23:45:21 // Generated by ComTest
 *
 */
public class OlutTest {
  // Generated by ComTest BEGIN
  /** testRekisteroi36 */
  @Test
  public void testRekisteroi36() {    // Olut: 36
    Olut kalja1 = new Olut(); 
    assertEquals("From: Olut line: 38", 0, kalja1.getId()); 
    kalja1.rekisteroi(); 
    Olut kalja2 = new Olut(); 
    kalja2.rekisteroi(); 
    int n1 = kalja1.getId(); 
    int n2 = kalja2.getId(); 
    assertEquals("From: Olut line: 44", n2-1, n1); 
  } // Generated by ComTest END
}